### ISSUE TITLE
db,logファイル残っている

### ISSUE THREAD

**Issue by ainehanta** [kuromike0629/ctf_server#1]
## gitignoreは？
指定はされてるみたいだけど，指定以前からaddしている可能性？

## 該当ファイル
`db/development.sqlite3`
`db/test.sqlite3`
`log/development.log`
`log/test.log`
`log/model.log`

## 対処法
`git rm {file path}`

**Comment by kuromike0629** [comment]
了解です。
対処しました。ありがとう
